name: MCP Server FastMCP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker image build -t Fast_MCP_Server:$(date +%s):v1 .
        docker push Fast_MCP_Server:$(date +%s):v1
